Country = 0
"Density\n(P/Km2)" = 0
Abbreviation = 7
"Agricultural Land( %)" = 7
"Land Area(Km2)" = 1
"Armed Forces size" = 24
"Birth Rate" = 6
"Calling Code" = 1
"Capital/Major City" = 3
Co2-Emissions = 7
CPI = 17
"CPI Change (%)" = 16
Currency-Code = 15
"Fertility Rate" = 7
"Forested Area (%)" = 7
"Gasoline Price" = 20
GDP = 2
"Gross primary education enrollment (%)" = 7
"Gross tertiary education enrollment (%)" = 12
"Infant mortality" = 6
"Largest city" = 6
"Life expectancy" = 8
"Maternal mortality ratio" = 14
"Minimum wage" = 45
"Official language" = 5
"Out of pocket health expenditure" = 7
"Physicians per thousand" = 7
Population = 1
"Population: Labor force participation (%)" = 19
"Tax revenue (%)" = 26
"Total tax rate" = 12
"Unemployment rate" = 19
Urban_population = 5
Latitude = 1
Longitude = 1
